
services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - Transcendance
    depends_on:
      - frontend
      - backend
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    networks:
      - Transcendance
    volumes:
      - ./backend/database:/app/database
    restart: unless-stopped
    env_file:
      - .env
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - Transcendance

networks:
  Transcendance:
    name : Transcendance
    driver : bridge
  
